// <auto-generated />
namespace A03.Envanter.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbnewkurulus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbnewkurulus));
        
        string IMigrationMetadata.Id
        {
            get { return "202301161243016_dbnewkurulus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
